# Generated by Django 4.2.1 on 2023-07-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necsproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobAlert',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('_time', models.DateTimeField(auto_now_add=True)),
                ('namealert', models.CharField(max_length=200, null=True)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('C', 'Critical')], max_length=200)),
                ('app', models.CharField(max_length=200, null=True)),
                ('owner', models.CharField(max_length=200, null=True)),
                ('result', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
