# Generated by Django 4.2.1 on 2023-07-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necsproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MANAGE_TICKET',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_attack', models.CharField(max_length=36)),
                ('severity', models.IntegerField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=200)),
                ('assignee', models.CharField(max_length=255)),
                ('reporter', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_id', to='necsproject.job')),
            ],
        ),
    ]
