# Generated by Django 4.2.1 on 2023-07-26 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('necsproject', '0003_alter_manage_ticket_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('search_name', models.CharField(max_length=200, null=True)),
                ('result_link', models.CharField(max_length=200, null=True)),
                ('results', models.TextField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobAlertDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('alert_detail_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_detail_assign', to='necsproject.jobalert')),
                ('assign', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=200, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('comment_person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_person', to=settings.AUTH_USER_MODEL)),
                ('job_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_detail_id', to='necsproject.jobalertdetail')),
            ],
        ),
    ]
