# Generated by Django 4.2.1 on 2023-07-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necsproject', '0004_alter_jobalert__time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobAlert',
            new_name='job',
        ),
    ]
